"""create db

Revision ID: 8b4fc7537d20
Revises: 
Create Date: 2021-06-06 14:10:05.233535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4fc7537d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('hash_password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('website', sa.VARCHAR(length=254), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=254), nullable=True),
    sa.Column('location', sa.VARCHAR(length=254), nullable=True),
    sa.Column('member_since', sa.DATETIME(), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
